CREATE DATABASE VAREJO;

USE VAREJO;

CREATE DATABASE MERCADINHO(
	
);
CREATE DATABASE CLIENTE();
CREATE DATABASE ENDERECOCLIENTE();
CREATE DATABASE FORNECEDOR();
CREATE DATABASE ENDERECOFORNECEDOR();
CREATE DATABASE PRODUTO();
CREATE DATABASE FUNCIONARIO();
CREATE DATABASE ENDERECOFUNCIONARIO();


DELIMITER $
CREATE PROCEDURE()
	BEGIN

	END
$

DELIMITER ;